### ISSUE TITLE
Querying a nested id.

### ISSUE THREAD

**Issue by atanasbozhkov** [codecapers/mongodb-rest#11]
I am using the latest version of mongodb-rest with mongodb 3.0.3. I am trying to get a record by filtering on a nested id. 

I have the following document in my Passport collection:

    "_id": {
        "$oid": "553a25f1bc2e8b53c7000002"
    }, 
    "answer": "none", 
    "password": "somePassword", 
    "provider": "local",  
    "user": {
        "$oid": "553a25f1bc2e8b53c7000001"
    }
    }

When I query all the results through mongodb-rest the structure changes to: 

     "_id": "553a25f1bc2e8b53c7000002", 
     "answer": "none", 
    "password": "somePassword", 
    "provider": "local",  
    "user": "553a25f1bc2e8b53c7000001"
    }

which I find simpler and cleaner - but inconsistent. 

I can filter the collection by the object _id by doing something like

    $ http http://localhost:8080/test/Passport/553a25f1bc2e8b53c7000002

which returns the correct result. 

I am trying to get the record by filtering on the user.id field. 
So when I tried to get it - I try the following request (as shown in the previous issue):

     $ http http://localhost:8080/test/Passport?query="{'user._id':'553a25f1bc2e8b53c7000001'}"

But it returns an empty set? I've also tried the following:

     $ http http://localhost:8080/test/Passport?query="{'user':{'_id':'553a25f1bc2e8b53c7000001'}}"

but it still returns an empty set. 
Any idea what the correct way of doing this is?

**Comment by atanasbozhkov** [comment]
I have implemented a fix in #12

**Comment by ashleydavis** [comment]
Talking about this in the pull request....
