### ISSUE TITLE
How to query for fields with special charactes

### ISSUE THREAD

**Issue by kishor-bhatt** [codecapers/mongodb-rest#20]
I have a collection - 
{
    "_id": ObjectID("56bda297b2d5c1be48a57ee4"),
    "enterprise_id": "56822fde6873dfac2912d29a",
    "employee_name": "Abc",
    "password": "abc",
    "mobile_number": "+912345678901",
    "alternate_mobile_number": [
        "+912345678902",
        "+912345678903"
    ],
    "employee_type": "P",
    "email_id": "",
    "country_name": "IND",
    "timezone": "GMT+05:30",
}

Now if I query for Name or other text fields it works, like query={"employee_name":"Abc"} or query={"enterprise_id": "56822fde6873dfac2912d29a"} 
But if fails for these - 
1) query={"mobile_number": "+912345678901"}
2) query={"alternate_mobile_number":["+919742765436","+919206964347"]}
3) query={"timezone": "GMT+05:30"}

Can somebody suggest how to query in these cases,are $regex supported by mongodb-rest ?? It will be helpful if can share with example.

**Comment by ashleydavis** [comment]
You need to uri encode when you want to include special characters in URLs.

For example query 1) should be encoded like this:

http://localhost:3000/test/test?query=%7B%22mobile_number%22%3A%20%22%2B912345678901%22%7D

You can encode a string using this online service:

http://meyerweb.com/eric/tools/dencoder/

Or if you can encode from JavaScript with `encodeURI`:

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURI
