### ISSUE TITLE
Windows-style carriage return error

### ISSUE THREAD

**Issue by sarahgp** [codecapers/mongodb-rest#6]
When I attempt to run `mongodb-rest` from the command line, I get the following error:

```
env: node\r: No such file or directory
```

Googling suggests this is an issue with DOS file encodings. [For instance.](https://github.com/mllrsohn/node-webkit-builder/issues/75)

I can work around it, but it should probably be updated.

**Comment by sarahgp** [comment]
In the meantime, this fix works, if anyone else needs it: https://github.com/mllrsohn/node-webkit-builder/issues/75#issuecomment-73423916

**Comment by ashleydavis** [comment]
So do I need to convert it to Unix line endings?

**Comment by sarahgp** [comment]
That's probably the easiest option. You could put the burden on users and note it in the read me, plus encourage people to download and use dos2unix, but just fixing it and pushing an updated package to npm is probably easiest.

**Comment by sarahgp** [comment]
If you do push a new package, you should also add this line to the `package.json`:
```json
"main": "server.js"
```

Right now, since the entry point isn't the default `index.js`, requiring the server instead of starting it on the command line fails.

**Comment by ashleydavis** [comment]
I've set "main" to "server.js". Please take a look a let me know if this is what you wanted.

**Comment by ashleydavis** [comment]
I've tried convert to Unix line endings, but only one file actually got changed. I used Sublime Text to make the changes. Did this do what you want?

**Comment by sarahgp** [comment]
It looks like you changed it in access-control. It is `bin` where I was running into trouble.

**Comment by ashleydavis** [comment]
Hmm... I try changing it in sublime but there is nothing to commit!

If you wanted to fork it and I'll change it I'll be happy to merge your change back.
